language: node_js
node_js:
  - '0.10'
before_script:
  - 'npm install -g bower grunt-cli'
  - 'bower install'
  - 'npm build'
deploy:
  provider: heroku
  app: readyapp
  api_key: "35efbe8ca8597471b7aa0b2c23fc9458b730f855"
  run:
    - "npm install -g grunt-cli"
    - "grunt build:development"